name: CI
 
on:
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: decK ping
      id: decK_ping
      uses: ./
      with:
        command: "ping"
        options: "--kong-addr http://localhost:8001"
    - name: decK validate
      id: decK_validate
      uses: ./
      with:
        command: "validate"
        options: "--kong-addr http://localhost:8001" 
        kong_workspaces: "kong"
    - name: decK diff
      id: decK_diff
      uses: ./
      with:
        command: "diff"
        options: "--kong-addr http://localhost:8001" 
        kong_workspaces: "kong"
